package com.example.plantarinn

import android.os.Parcel
import android.os.Parcelable

//One time unit, eg: 60 minutes in 1 hour, 60 seconds in 1 minute....
private const val ONE_UNIT_TIME = 60

//Doing the "default parameter" way of achieving constructor overloading
class PlantPlan constructor(val hours: Int, val minutes: Int, var numberOfPlants: Int? = null, _numberOfBakkar: Int? = null, _bakkaSize: Int? = null) :
    Parcelable {

    //Should be the total planting time measured in seconds
    private val totalTimeS: Int
    val plantInterval: Float
    //Auto generated by android studio. Makes it so that this object can be sent to another Activity!
    constructor(parcel: Parcel) : this(
        parcel.readInt(),
        parcel.readInt(),
        parcel.readValue(Int::class.java.classLoader) as? Int
    ) {
    }

    init {
        if (_numberOfBakkar != null && _bakkaSize != null) {
            numberOfPlants = _numberOfBakkar * _bakkaSize
        }

        totalTimeS = (hours * ONE_UNIT_TIME * ONE_UNIT_TIME) + (minutes * ONE_UNIT_TIME)
        plantInterval = (totalTimeS.toFloat() / numberOfPlants?.toFloat()!!)
    }

    override fun writeToParcel(parcel: Parcel, flags: Int) {
        parcel.writeInt(hours)
        parcel.writeInt(minutes)
        parcel.writeValue(numberOfPlants)
    }

    override fun describeContents(): Int {
        return 0
    }

    companion object CREATOR : Parcelable.Creator<PlantPlan> {
        override fun createFromParcel(parcel: Parcel): PlantPlan {
            return PlantPlan(parcel)
        }

        override fun newArray(size: Int): Array<PlantPlan?> {
            return arrayOfNulls(size)
        }
    }


}